"""Ajouter authentification aux contacts

Revision ID: 090ed5aae977
Revises: 22667a760a76
Create Date: 2025-10-12 17:11:21.935394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090ed5aae977'
down_revision = '22667a760a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_contacts_username', ['username'])
        batch_op.create_unique_constraint('uq_contacts_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contacts_email', type_='unique')
        batch_op.drop_constraint('uq_contacts_username', type_='unique')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
