"""Ajouter modules notifications et workflow

Revision ID: 22667a760a76
Revises: 4237142c9582
Create Date: 2025-10-12 16:40:31.392294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22667a760a76'
down_revision = '4237142c9582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('titre_template', sa.String(length=300), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('type_notification', sa.Enum('RAPPEL_RAPPORT', 'VALIDATION_RAPPORT', 'REJET_RAPPORT', 'ALERTE_DONNEES', 'MESSAGE_SYSTEME', 'MAINTENANCE_PLANIFIEE', 'INCIDENT_TECHNIQUE', 'NOUVELLE_REGLEMENTATION', name='typenotification'), nullable=False),
    sa.Column('priorite_defaut', sa.Integer(), nullable=True),
    sa.Column('url_template', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('validateurs_designes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('validateur_id', sa.Integer(), nullable=False),
    sa.Column('type_rapport', sa.Enum('PRODUCTION', 'TRANSPORT', 'DISTRIBUTION', 'MAINTENANCE', 'INCIDENT', 'FINANCIER', 'TECHNIQUE', 'ENVIRONNEMENTAL', name='typerapport'), nullable=False),
    sa.Column('niveau_validation', sa.Integer(), nullable=True),
    sa.Column('peut_valider_urgent', sa.Boolean(), nullable=True),
    sa.Column('delai_max_validation', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('type_rapport', sa.Enum('PRODUCTION', 'TRANSPORT', 'DISTRIBUTION', 'MAINTENANCE', 'INCIDENT', 'FINANCIER', 'TECHNIQUE', 'ENVIRONNEMENTAL', name='typerapport'), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('etapes', sa.Text(), nullable=True),
    sa.Column('delai_validation', sa.Integer(), nullable=True),
    sa.Column('validateurs_requis', sa.Integer(), nullable=True),
    sa.Column('rappel_automatique', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_rapport')
    )
    op.create_table('validations_rapport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.Column('type_rapport', sa.Enum('PRODUCTION', 'TRANSPORT', 'DISTRIBUTION', 'MAINTENANCE', 'INCIDENT', 'FINANCIER', 'TECHNIQUE', 'ENVIRONNEMENTAL', name='typerapport'), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('validateur_id', sa.Integer(), nullable=True),
    sa.Column('etape', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'SOUMIS', 'EN_VALIDATION', 'VALIDE', 'REJETE', 'EXPIRE', name='statutworkflow'), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('signature_electronique', sa.String(length=255), nullable=True),
    sa.Column('donnees_originales', sa.Text(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=True),
    sa.Column('rappels_envoyes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validations_rapport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validations_rapport_rapport_id'), ['rapport_id'], unique=False)

    op.create_table('historique_validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATION', 'SOUMISSION', 'VALIDATION', 'REJET', 'MODIFICATION', 'EXPIRATION', 'RELANCE', name='typeaction'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('donnees_avant', sa.Text(), nullable=True),
    sa.Column('donnees_apres', sa.Text(), nullable=True),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['validation_id'], ['validations_rapport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historique_validation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historique_validation_rapport_id'), ['rapport_id'], unique=False)

    op.create_table('messages_internes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=300), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('archive_expediteur', sa.Boolean(), nullable=False),
    sa.Column('archive_destinataire', sa.Boolean(), nullable=False),
    sa.Column('message_parent_id', sa.Integer(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destinataire_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_parent_id'], ['messages_internes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RAPPEL_RAPPORT', 'VALIDATION_RAPPORT', 'REJET_RAPPORT', 'ALERTE_DONNEES', 'MESSAGE_SYSTEME', 'MAINTENANCE_PLANIFIEE', 'INCIDENT_TECHNIQUE', 'NOUVELLE_REGLEMENTATION', name='typenotification'), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('archivee', sa.Boolean(), nullable=False),
    sa.Column('url_action', sa.String(length=500), nullable=True),
    sa.Column('donnees_json', sa.Text(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=True),
    sa.Column('rapport_type', sa.String(length=50), nullable=True),
    sa.Column('rapport_id', sa.Integer(), nullable=True),
    sa.Column('operateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rappel_rapport', sa.Boolean(), nullable=True),
    sa.Column('validation_rapport', sa.Boolean(), nullable=True),
    sa.Column('rejet_rapport', sa.Boolean(), nullable=True),
    sa.Column('alerte_donnees', sa.Boolean(), nullable=True),
    sa.Column('message_systeme', sa.Boolean(), nullable=True),
    sa.Column('maintenance_planifiee', sa.Boolean(), nullable=True),
    sa.Column('incident_technique', sa.Boolean(), nullable=True),
    sa.Column('nouvelle_reglementation', sa.Boolean(), nullable=True),
    sa.Column('notifications_email', sa.Boolean(), nullable=True),
    sa.Column('notifications_browser', sa.Boolean(), nullable=True),
    sa.Column('digest_quotidien', sa.Boolean(), nullable=True),
    sa.Column('digest_hebdomadaire', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences_notifications')
    op.drop_table('notifications')
    op.drop_table('messages_internes')
    with op.batch_alter_table('historique_validation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historique_validation_rapport_id'))

    op.drop_table('historique_validation')
    with op.batch_alter_table('validations_rapport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validations_rapport_rapport_id'))

    op.drop_table('validations_rapport')
    op.drop_table('workflows')
    op.drop_table('validateurs_designes')
    op.drop_table('templates_notifications')
    # ### end Alembic commands ###
