"""Ajout module operateurs

Revision ID: 3a076f339758
Revises: 
Create Date: 2025-10-12 06:13:06.113411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a076f339758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('fonction', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
