"""Add atteint field to KPIStrategic

Revision ID: 4aa9995541d7
Revises: 9bcea24bd95d
Create Date: 2025-10-16 06:56:54.179694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa9995541d7'
down_revision = '9bcea24bd95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi_strategic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atteint', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transformateurs_distribution', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transformateurs_distribution', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('kpi_strategic', schema=None) as batch_op:
        batch_op.drop_column('atteint')

    # ### end Alembic commands ###
