"""Fix KPI unique constraint - allow same code for different years

Revision ID: 606408eb352b
Revises: 78ccdab3df76
Create Date: 2025-10-12 20:19:57.405648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606408eb352b'
down_revision = '78ccdab3df76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi_strategic', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kpi_code_annee_operateur', ['code', 'annee', 'operateur_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpi_strategic', schema=None) as batch_op:
        batch_op.drop_constraint('uq_kpi_code_annee_operateur', type_='unique')

    # ### end Alembic commands ###
