"""Add ARE dashboard models

Revision ID: 78ccdab3df76
Revises: 090ed5aae977
Create Date: 2025-10-12 20:15:29.572237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ccdab3df76'
down_revision = '090ed5aae977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donnees_province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('taux_acces_electricite', sa.Float(), nullable=True),
    sa.Column('puissance_installee', sa.Float(), nullable=True),
    sa.Column('production_annuelle', sa.Float(), nullable=True),
    sa.Column('nombre_operateurs', sa.Integer(), nullable=True),
    sa.Column('investissements', sa.Float(), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicateur_sectoriel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('categorie', sa.Enum('PRODUCTION', 'TRANSPORT', 'DISTRIBUTION', 'ACCES', 'QUALITE', 'FINANCIER', 'ENVIRONNEMENTAL', name='categorieindicateur'), nullable=False),
    sa.Column('sous_categorie', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('evolution', sa.Float(), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('operateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_strategic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('tendance', sa.Enum('HAUSSE', 'BAISSE', 'STABLE', name='tendancekpi'), nullable=False),
    sa.Column('evolution_pourcentage', sa.Float(), nullable=True),
    sa.Column('objectif', sa.Float(), nullable=True),
    sa.Column('seuil_alerte', sa.Float(), nullable=True),
    sa.Column('source_donnees', sa.String(length=200), nullable=True),
    sa.Column('operateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('alerte_regulateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('CONFORMITE', 'FINANCIER', 'TECHNIQUE', 'ADMINISTRATIF', 'SECURITE', name='typealerte'), nullable=False),
    sa.Column('severite', sa.Enum('FAIBLE', 'MOYENNE', 'ELEVEE', 'CRITIQUE', name='severitealerte'), nullable=False),
    sa.Column('entite_concernee', sa.String(length=200), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('date_resolution', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('actions_recommandees', sa.Text(), nullable=True),
    sa.Column('priorite', sa.Integer(), nullable=True),
    sa.Column('operateur_id', sa.Integer(), nullable=True),
    sa.Column('createur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapport_annuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('contenu_json', sa.JSON(), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.Column('date_finalisation', sa.DateTime(), nullable=True),
    sa.Column('nombre_operateurs', sa.Integer(), nullable=True),
    sa.Column('periode_debut', sa.Date(), nullable=True),
    sa.Column('periode_fin', sa.Date(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rapport_annuel')
    op.drop_table('alerte_regulateur')
    op.drop_table('kpi_strategic')
    op.drop_table('indicateur_sectoriel')
    op.drop_table('donnees_province')
    # ### end Alembic commands ###
