"""Ajout KPIs réglementaires RDC

Revision ID: 9bcea24bd95d
Revises: 55a9b4e2f367
Create Date: 2025-10-15 20:34:17.486705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcea24bd95d'
down_revision = '55a9b4e2f367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis_reglementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_kpi', sa.Enum('QUALITE_SERVICE', 'CONFORMITE_TECHNIQUE', 'DELAIS_RACCORDEMENT', 'TARIFICATION', 'FACTURATION', 'REPORTING', 'MAINTENANCE', 'ENVIRONNEMENT', name='typekpireglementaire'), nullable=False),
    sa.Column('seuil_excellent', sa.Float(), nullable=True),
    sa.Column('seuil_acceptable', sa.Float(), nullable=True),
    sa.Column('seuil_limite', sa.Float(), nullable=True),
    sa.Column('seuil_critique', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=50), nullable=True),
    sa.Column('sens_amelioration', sa.String(length=20), nullable=True),
    sa.Column('penalite_moderee', sa.Float(), nullable=True),
    sa.Column('penalite_majeure', sa.Float(), nullable=True),
    sa.Column('penalite_critique', sa.Float(), nullable=True),
    sa.Column('reference_legale', sa.String(length=500), nullable=True),
    sa.Column('autorite_controle', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('performances_operateur_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('valeur_mesuree', sa.Float(), nullable=False),
    sa.Column('evaluation', sa.String(length=50), nullable=True),
    sa.Column('penalite_appliquee', sa.Float(), nullable=True),
    sa.Column('verifie', sa.Boolean(), nullable=True),
    sa.Column('date_verification', sa.DateTime(), nullable=True),
    sa.Column('verifiee_par', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis_reglementaires.id'], ),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.ForeignKeyConstraint(['verifiee_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanctions_reglementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('performance_kpi_id', sa.Integer(), nullable=True),
    sa.Column('type_sanction', sa.String(length=100), nullable=True),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('montant_amende', sa.Float(), nullable=True),
    sa.Column('date_infraction', sa.Date(), nullable=False),
    sa.Column('date_notification', sa.Date(), nullable=True),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('emise_par', sa.String(length=200), nullable=True),
    sa.Column('numero_decision', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.ForeignKeyConstraint(['performance_kpi_id'], ['performances_operateur_kpi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed drop_table for sqlite_sequence as it's a system table in SQLite
    with op.batch_alter_table('transformateurs_distribution', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transformateurs_distribution', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # Removed create_table for sqlite_sequence as it's a system table in SQLite
    op.drop_table('sanctions_reglementaires')
    op.drop_table('performances_operateur_kpi')
    op.drop_table('kpis_reglementaires')
    # ### end Alembic commands ###
