"""Ajout module production hydroelectrique

Revision ID: e35f9a22a267
Revises: 3a076f339758
Create Date: 2025-10-12 06:45:06.954276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35f9a22a267'
down_revision = '3a076f339758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centrales_hydro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('localisation', sa.String(length=200), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('cours_eau', sa.String(length=100), nullable=True),
    sa.Column('puissance_installee', sa.Float(), nullable=True),
    sa.Column('puissance_disponible', sa.Float(), nullable=True),
    sa.Column('hauteur_chute', sa.Float(), nullable=True),
    sa.Column('debit_equipement', sa.Float(), nullable=True),
    sa.Column('type_centrale', sa.String(length=50), nullable=True),
    sa.Column('nombre_groupes', sa.Integer(), nullable=True),
    sa.Column('nombre_transformateurs', sa.Integer(), nullable=True),
    sa.Column('tension_evacuation', sa.String(length=50), nullable=True),
    sa.Column('date_mise_service', sa.DateTime(), nullable=True),
    sa.Column('date_derniere_revision', sa.DateTime(), nullable=True),
    sa.Column('constructeur', sa.String(length=100), nullable=True),
    sa.Column('annee_construction', sa.Integer(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('centrales_hydro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centrales_hydro_nom'), ['nom'], unique=False)

    op.create_table('rapports_hydro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('centrale_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('periode_debut', sa.DateTime(), nullable=False),
    sa.Column('periode_fin', sa.DateTime(), nullable=False),
    sa.Column('niveau_retenue_moyen', sa.Float(), nullable=True),
    sa.Column('niveau_retenue_min', sa.Float(), nullable=True),
    sa.Column('niveau_retenue_max', sa.Float(), nullable=True),
    sa.Column('debit_moyen', sa.Float(), nullable=True),
    sa.Column('debit_min', sa.Float(), nullable=True),
    sa.Column('debit_max', sa.Float(), nullable=True),
    sa.Column('volume_turbiné', sa.Float(), nullable=True),
    sa.Column('energie_produite', sa.Float(), nullable=True),
    sa.Column('energie_disponible', sa.Float(), nullable=True),
    sa.Column('facteur_charge', sa.Float(), nullable=True),
    sa.Column('temps_fonctionnement', sa.Float(), nullable=True),
    sa.Column('nombre_arrets', sa.Integer(), nullable=True),
    sa.Column('duree_arrets', sa.Float(), nullable=True),
    sa.Column('rendement_global', sa.Float(), nullable=True),
    sa.Column('rendement_turbine', sa.Float(), nullable=True),
    sa.Column('rendement_alternateur', sa.Float(), nullable=True),
    sa.Column('maintenances_preventives', sa.Integer(), nullable=True),
    sa.Column('maintenances_correctives', sa.Integer(), nullable=True),
    sa.Column('incidents_majeurs', sa.Integer(), nullable=True),
    sa.Column('description_incidents', sa.Text(), nullable=True),
    sa.Column('debit_reserve', sa.Float(), nullable=True),
    sa.Column('impact_environnemental', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('validé_par', sa.String(length=100), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['centrale_id'], ['centrales_hydro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donnees_mensuelles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.Integer(), nullable=False),
    sa.Column('niveau_retenue', sa.Float(), nullable=True),
    sa.Column('debit_turbiné', sa.Float(), nullable=True),
    sa.Column('debit_déversé', sa.Float(), nullable=True),
    sa.Column('cote_aval', sa.Float(), nullable=True),
    sa.Column('energie_produite', sa.Float(), nullable=True),
    sa.Column('puissance_moyenne', sa.Float(), nullable=True),
    sa.Column('puissance_max', sa.Float(), nullable=True),
    sa.Column('heures_fonctionnement', sa.Float(), nullable=True),
    sa.Column('temperature_moyenne', sa.Float(), nullable=True),
    sa.Column('pluviometrie', sa.Float(), nullable=True),
    sa.Column('evenements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapports_hydro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupes_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.Column('numero_groupe', sa.String(length=10), nullable=False),
    sa.Column('nom_groupe', sa.String(length=100), nullable=True),
    sa.Column('puissance_nominale', sa.Float(), nullable=True),
    sa.Column('tension_nominale', sa.Float(), nullable=True),
    sa.Column('vitesse_rotation', sa.Float(), nullable=True),
    sa.Column('type_turbine', sa.String(length=50), nullable=True),
    sa.Column('heures_fonctionnement', sa.Float(), nullable=True),
    sa.Column('energie_produite', sa.Float(), nullable=True),
    sa.Column('puissance_moyenne', sa.Float(), nullable=True),
    sa.Column('puissance_max', sa.Float(), nullable=True),
    sa.Column('nombre_arrets_programme', sa.Integer(), nullable=True),
    sa.Column('nombre_arrets_force', sa.Integer(), nullable=True),
    sa.Column('duree_arrets_programme', sa.Float(), nullable=True),
    sa.Column('duree_arrets_force', sa.Float(), nullable=True),
    sa.Column('rendement_moyen', sa.Float(), nullable=True),
    sa.Column('facteur_charge', sa.Float(), nullable=True),
    sa.Column('disponibilite', sa.Float(), nullable=True),
    sa.Column('date_derniere_revision', sa.DateTime(), nullable=True),
    sa.Column('type_derniere_revision', sa.String(length=100), nullable=True),
    sa.Column('prochaine_revision', sa.DateTime(), nullable=True),
    sa.Column('incidents', sa.Text(), nullable=True),
    sa.Column('travaux_realises', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapports_hydro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transformateurs_rapport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('rapport_id', sa.Integer(), nullable=False),
    sa.Column('numero_transformateur', sa.String(length=10), nullable=False),
    sa.Column('nom_transformateur', sa.String(length=100), nullable=True),
    sa.Column('puissance_nominale', sa.Float(), nullable=True),
    sa.Column('tension_primaire', sa.Float(), nullable=True),
    sa.Column('tension_secondaire', sa.Float(), nullable=True),
    sa.Column('type_refroidissement', sa.String(length=50), nullable=True),
    sa.Column('energie_transferee', sa.Float(), nullable=True),
    sa.Column('heures_service', sa.Float(), nullable=True),
    sa.Column('charge_moyenne', sa.Float(), nullable=True),
    sa.Column('charge_max', sa.Float(), nullable=True),
    sa.Column('temperature_huile_moyenne', sa.Float(), nullable=True),
    sa.Column('temperature_huile_max', sa.Float(), nullable=True),
    sa.Column('temperature_enroulements_max', sa.Float(), nullable=True),
    sa.Column('etat_general', sa.String(length=50), nullable=True),
    sa.Column('date_derniere_maintenance', sa.DateTime(), nullable=True),
    sa.Column('type_maintenance', sa.String(length=100), nullable=True),
    sa.Column('prochaine_maintenance', sa.DateTime(), nullable=True),
    sa.Column('incidents', sa.Text(), nullable=True),
    sa.Column('travaux_realises', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rapport_id'], ['rapports_hydro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformateurs_rapport')
    op.drop_table('groupes_production')
    op.drop_table('donnees_mensuelles')
    op.drop_table('rapports_hydro')
    with op.batch_alter_table('centrales_hydro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centrales_hydro_nom'))

    op.drop_table('centrales_hydro')
    # ### end Alembic commands ###
