"""Ajout champs manquants centrales et rapports

Revision ID: fad89811421e
Revises: e35f9a22a267
Create Date: 2025-10-12 06:47:18.854294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad89811421e'
down_revision = 'e35f9a22a267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centrales_hydro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_turbine', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type_barrage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('niveau_tension', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('superficie_bassin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volume_retenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('statut', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('rapports_hydro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_transmission', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapports_hydro', schema=None) as batch_op:
        batch_op.drop_column('date_transmission')

    with op.batch_alter_table('centrales_hydro', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('statut')
        batch_op.drop_column('volume_retenue')
        batch_op.drop_column('superficie_bassin')
        batch_op.drop_column('niveau_tension')
        batch_op.drop_column('type_barrage')
        batch_op.drop_column('type_turbine')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
